version: '3.9'

services:
  flask:
    container_name: flask
    build: .
    ports:
    - 8080:5000
    volumes:
    - ./:/var/www/html
    networks:
    - internal

networks:
  internal:
    driver: "bridge"
